### ISSUE TITLE
安装需要的log目录你吃了？

### ISSUE THREAD

**Issue by yublog** [jiix/xiunobbs#1]
安装需要的log目录你吃了？

**Comment by zwying0814** [comment]
自己手动创建一个不香嘛

**Comment by yublog** [comment]
不是吧，目录是空的？感觉不太专业的样子哎







在 2020-08-09 09:45:07，"zwying0814" <notifications@github.com> 写道：

自己手动创建一个不香嘛

**Comment by jiix** [comment]
请下载发布版。
https://github.com/jiix/xiunobbs/releases
