### ISSUE TITLE
4.1.0以后install包有个问题！

### ISSUE THREAD

**Issue by ittking** [jiix/xiunobbs#14]
tmp文件授权了，无效，一直检测失败，手动授权后，依旧检测失败，如果直接禁止tmp文件检测，安装后无法正常访问！

**Comment by he21o** [comment]
自己在配置换tmp存储目录

**Comment by he21o** [comment]
大概在index.php里面就可以搞

**Comment by jiix** [comment]
最新版本暂时只有[v4.0.7](https://github.com/jiix/xiunobbs/releases/tag/v4.0.7)。
temp是必要目录，请设置正确权限和用户。目录权限通常是755，用户名（用户组）一般是www或www-data而非root。如果使用AMH面板，可以选中文件，设置权限时使用“一键给予读写权限”。

**Comment by bigcaibao** [comment]
@jiix 您这个项目还在继续开发嘛?

**Comment by jiix** [comment]
> @jiix 您这个项目还在继续开发嘛?

推荐大家拥抱新技术。
