### ISSUE TITLE
请问如何修改，实现程序在初始化时解决emoji显示问题

### ISSUE THREAD

**Issue by Airhelym** [jiix/xiunobbs#16]
因为我自用的是4.0.4原版，自己修改了些文件，不大想从头再来。
我修改了install目录下的alter.sql和install.sql，将其中的utf8均替换为utf8mb4。但安装后数据库变成utf8mb4，但conf/conf.php仍是utf8。
请教一下，还有哪些地方需要修改，使其安装后生成的conf.php文件中的编码也更新？

**Comment by Airhelym** [comment]
问题刚才已经解决

**Comment by Mitpoppy** [comment]
> 问题刚才已经解决

建议把解决方法说一下，说不定就帮助到后来者了

**Comment by Airhelym** [comment]
/install/alter.sql
第9行 CHARSET=utf8 COLLATE=utf8_general_ci; 改为 CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_520_ci

/install/install.sql
第32行 CHARSET=utf8; 改为 CHARSET=utf8mb4;
第55、92、107、134、145、166、192、200、210、229、238、255、264、273、283、301行 CHARSET=utf8 COLLATE=utf8_general_ci; 改为 CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_520_ci;

/conf/conf.default.php
第21、33行 'charset' => 'utf8' 改为 'charset' => 'utf8mb4'

【修改成 utf8mb4_unicode_ci 的部分也可以改为 utf8mb4_general_ci】
这是我目前修改的策略，直接基于4.0.4改的。这样可以单独解决emoji问题，初始化时自动完成。可能有点班门弄斧
