### ISSUE TITLE
There are XSS vulnerabilities in the site introduction of the background setting interface

### ISSUE THREAD

**Issue by mlws1900** [jiix/xiunobbs#24]
After logging in, visit this link http://127.0.0.0.0.3/admin/?setting-base.htm
![mlws](https://github.com/jiix/xiunobbs/assets/88109145/b6fa25b6-2dda-4cee-b008-621fde973716)
Enter Payload in the site introduction box
<script> Alert (/mlws1900/) </script>
Later, click to save
Visit the homepage again, that is, the storage XSS will be displayed
![1](https://github.com/jiix/xiunobbs/assets/88109145/5a836451-d003-4a4f-b1cf-99a3ecd075e4)

**Comment by jiix** [comment]
You're admin.
