### ISSUE TITLE
About里的链接域名，这么快就不续费了吗？

### ISSUE THREAD

**Issue by totemtec** [jiix/xiunobbs#6]
www.jiih.com

**Comment by jiix** [comment]
没钱续费，不要了。😅

**Comment by zhuanyessr** [comment]
> 没钱续费，不要了。😅

大佬，怎么不续费了呢？另外有计划做个交流论坛之类的吗

**Comment by jiix** [comment]
> > 没钱续费，不要了。😅
> 
> 大佬，怎么不续费了呢？另外有计划做个交流论坛之类的吗

其实域名早已续满10年，只是没时间启用。
交流可以在 [https://github.com/jiix/xiunobbs/discussions](https://github.com/jiix/xiunobbs/discussions)，没必要单独做交流论坛。
