### ISSUE TITLE
能否加入 通过链接插入媒体 的功能？

### ISSUE THREAD

**Issue by NextFutureOfficial** [jiix/xiunobbs#7]
由于服务器存储空间小，并且链接速度慢，一般情况下上传图片都采用图床链接嵌入的方式，但是我找了很久，也尝试过不同的编辑器，百度编辑器不支持嵌入图片链接（甚至连切换成HTML格式编辑都不行（悲），大白编辑器装上去貌似直接用不了（）dalao能否给编辑器加入一个“HTML编辑模式”和“可视化编辑模式“的切换按钮，或者新增一个 “通过URL嵌入图片” 的功能呢（）

**Comment by jiix** [comment]
百度编辑器可以用源码的方式插入图片，把图床提供的html标签粘贴进去就好。
![test](https://user-images.githubusercontent.com/48614618/108487731-8bdebf00-72da-11eb-9b63-a87f43e87893.gif)

**Comment by NextFutureOfficial** [comment]
！感谢dalao不过我好像用的是手机版，并没有康到这个按钮哇（悲）

**Comment by NextFutureOfficial** [comment]
啊！对不起对不起我看了一下用电脑也一样不显示，可能我这个编辑器是精简版的吧，用的是大佬源码里自带的那个（）我去找找完整版的编辑器

**Comment by jiix** [comment]
截图就是xiunobbs-4.0.7.zip中默认配置的编辑器。你可以把`plugin/xn_umeditor`里的文件直接替换，并清空缓存。
这些按钮都可以在配置文件中设置是否显示。

**Comment by NextFutureOfficial** [comment]
首先感谢dalao的回复！

已经尝试重新下载本项目提供的 `xiunobbs-4.0.7.zip` 压缩文件。提取其中`plugin/xn_umeditor`的文件更换到现有网站目录，仍然不起作用。

配置文件是默认的，没有经过任何修改，现在怀疑是否为设备问题。
我使用手机系统是MIUI12稳定版，用 `小米浏览器` 和微软的 `Edge浏览器` 均无法正常显示如您图中出现的所有按钮，同时使用iOS11的 `Safari` 测试同样无法完全显示，依然只有我先前上传的图片中那几个。如果可以的话，dalao能否用手机看看问题是否能复现呢（）

**Comment by NextFutureOfficial** [comment]
**补充情况描述**
我尝试更改了 `config.xmeditor.js` 文件中的相关配置，但我发现貌似并没有对我论坛的编辑器产生对应的影响，是否有可能编辑器作者针对手机做了特殊适配使得手机和电脑的编辑器界面独立？（由于没有电脑，我无法测试在电脑浏览器环境下编辑器是否能正常工作）
![Screenshot_2021-02-21-00-39-28-573_com android browser](https://user-images.githubusercontent.com/61616918/108612744-1db8fb80-73b1-11eb-9945-c148838935b1.jpg)
![Screenshot_2021-02-21-00-42-58-824_com android browser](https://user-images.githubusercontent.com/61616918/108612748-290c2700-73b1-11eb-826a-9eac7f604048.jpg)

**Comment by jiix** [comment]
重新添加了大白·TinyMCE编辑器，可以试一下。

**Comment by NextFutureOfficial** [comment]
好的，感谢dalao
